[package]
name = "knot-grpc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures = "0.3.32"
hyper = "1.10.1"
hyper-util = "0.1.20"
interprocess = { version = "2.4.2", features = ["tokio"] }
tonic = "0.14.6"
tower = "0.5.3"
tracing = "0.1.44"
tokio = "1.52.3"

[dev-dependencies]
futures = { version = "0.3.32", features = ["executor"] }
tempfile = "3.27.0"
tokio-stream = "0.1.18"
prost = "0.14.4"
tonic-prost = "0.14.6"

[[test]]
name = "integration"
path = "tests/integration_tests.rs"
[build-dependencies]
tonic-prost-build = "0.14.6"
protox = "0.9.1"
