//! # Knot Messages
//!
//! This module defines the core message structures used for communication
//! between the Knot CLI and the Knot Daemon.
//!
//! The module supports three interaction patterns:
//! 1. **Requests**: Initiated by the client, requiring a correlated response.
//! 2. **Responses**: Sent by the server in reply to a specific request (matched via ID).
//! 3. **Events**: One-way asynchronous notifications (e.g., logs or status updates)
//!    that do not require an acknowledgment.

use crate::{
    codec::MessageCodec,
    transport::{MessageTransport, RawTransport},
};
use knot_core::errors::TransportError;
use knot_core::utils::TimestampUtils;
use serde::{Deserialize, Serialize, de::DeserializeOwned};

pub mod daemon;

/// The primary envelope for all system communication.
///
/// `Message` wraps payloads of types `Req`, `Res`, or `Ev` to provide
/// metadata required for tracking, synchronization, and timestamping.
#[derive(Debug, Serialize, Deserialize)]
pub struct Message<Req, Res, Ev> {
    /// Unique correlation ID. For requests, generated by the client;
    /// for responses, matches the ID of the original request.
    /// For events, this is typically set to 0.
    pub id: u32,
    /// Unix timestamp in milliseconds, captured at the moment of message creation.
    pub timestamp: u64,
    /// The message type and its associated payload.
    pub kind: MessageKind<Req, Res, Ev>,
}

pub struct MessageContext<'a, R, Req, Res, Ev, Cod>
where
    R: RawTransport + 'static,
{
    transport: &'a MessageTransport<R, Req, Res, Ev, Cod>,
    message: Message<Req, Res, Ev>,
    replied: bool,
}
impl<'a, R, Req, Res, Ev, Cod> MessageContext<'a, R, Req, Res, Ev, Cod>
where
    R: RawTransport + 'static,
    Req: Serialize + DeserializeOwned + Send + 'static,
    Res: Serialize + DeserializeOwned + Send + 'static,
    Ev: Serialize + DeserializeOwned + Send + 'static,
    Cod: MessageCodec<Raw = Vec<u8>> + Send + 'static,
{
    pub fn new(
        message: Message<Req, Res, Ev>,
        transport: &'a MessageTransport<R, Req, Res, Ev, Cod>,
    ) -> Self {
        Self {
            transport,
            message,
            replied: false,
        }
    }

    pub async fn reply(&mut self, msg: Res) -> Result<(), TransportError> {
        if !self.replied {
            eprintln!(
                "WARNING: MessageContext replied twice to request ID {}",
                self.message.id
            );
        }

        self.replied = true;
        self.transport
            .send(Message::response(self.message.id, msg))
            .await
    }

    pub async fn emit(&self, msg: Message<Req, Res, Ev>) -> Result<(), TransportError> {
        self.transport.send(msg).await
    }

    pub fn get(&self) -> &Message<Req, Res, Ev> {
        &self.message
    }

    pub fn kind(&self) -> &MessageKind<Req, Res, Ev> {
        &self.message.kind
    }

    pub fn into_parts(
        self,
    ) -> (
        Message<Req, Res, Ev>,
        &'a MessageTransport<R, Req, Res, Ev, Cod>,
    ) {
        (self.message, self.transport)
    }
}

/// Differentiates between the roles of a message within the protocol.
#[derive(Debug, Serialize, Deserialize)]
pub enum MessageKind<Req, Res, Ev> {
    /// A request sent from a client to a server.
    Request(Req),
    /// A response sent from a server back to a client.
    Response(Res),
    /// An asynchronous event or notification from the server.
    Event(Ev),
}

impl<Req, Res, Ev> Message<Req, Res, Ev>
where
    Req: Serialize,
    Res: Serialize,
    Ev: Serialize,
{
    fn new(id: u32, kind: MessageKind<Req, Res, Ev>) -> Self {
        Self {
            id,
            timestamp: TimestampUtils::now_ms(),
            kind,
        }
    }

    /// Creates a new `Message` initialized as a **Request**.
    ///
    /// Automatically captures the current system time using `TimestampUtils`.
    ///
    /// # Arguments
    /// * `id` - A unique identifier for this request.
    /// * `payload` - The specific data for the request.
    pub fn request(id: u32, payload: Req) -> Self {
        Self::new(id, MessageKind::Request(payload))
    }

    /// Creates a new `Message` initialized as a **Response**.
    ///
    /// The `id` should match the `id` of the request this response is addressing.
    ///
    /// # Arguments
    /// * `id` - The correlation ID from the original request.
    /// * `payload` - The specific data for the response.
    pub fn response(id: u32, payload: Res) -> Self {
        Self::new(id, MessageKind::Response(payload))
    }

    /// Creates a new `Message` initialized as an **Event**.
    ///
    /// Events are one-way notifications and use `id: 0` by default,
    /// as they do not participate in a request-response correlation loop.
    ///
    /// # Arguments
    /// * `payload` - The event data (e.g., a broadcast notification).
    pub fn event(payload: Ev) -> Self {
        Self::new(0, MessageKind::Event(payload))
    }

    /// Returns the correlation ID of this message.
    pub fn id(&self) -> u32 {
        self.id
    }

    /// Consumes the message and returns the ID and request payload.
    ///
    /// Returns `None` if the message is actually a `Response`.
    pub fn into_request(self) -> Option<(u32, Req)> {
        match self.kind {
            MessageKind::Request(payload) => Some((self.id, payload)),
            _ => None,
        }
    }

    /// Consumes the message and returns the ID and response payload.
    ///
    /// Returns `None` if the message is actually a `Request`.
    pub fn into_response(self) -> Option<(u32, Res)> {
        match self.kind {
            MessageKind::Response(payload) => Some((self.id, payload)),
            _ => None,
        }
    }

    /// Consumes the message and returns the payload of the event.
    /// Returns `None` if the message is not an `Event`.
    pub fn into_event(self) -> Option<(u32, Ev)> {
        match self.kind {
            MessageKind::Event(payload) => Some((self.id, payload)),
            _ => None,
        }
    }

    /// Returns `true` if the message is a `Request`.
    pub fn is_request(&self) -> bool {
        matches!(self.kind, MessageKind::Request(_))
    }

    /// Returns `true` if the message is a `Response`.
    pub fn is_response(&self) -> bool {
        matches!(self.kind, MessageKind::Response(_))
    }

    /// Returns `true` if the message is an `Event`.
    pub fn is_event(&self) -> bool {
        matches!(self.kind, MessageKind::Event(_))
    }
}
