//! # Knot Messages
//!
//! This module defines the core message structures used for communication
//! between the Knot CLI and the Knot Daemon.
//!
//! The module supports three interaction patterns:
//! 1. **Requests**: Initiated by the client, requiring a correlated response.
//! 2. **Responses**: Sent by the server in reply to a specific request (matched via ID).
//! 3. **Events**: One-way asynchronous notifications (e.g., logs or status updates)
//!    that do not require an acknowledgment.

use crate::transport::{MessageTransport, RawTransport, TransportSpec};
use knot_core::errors::TransportError;
use knot_core::utils::TimestampUtils;
use serde::{Deserialize, Serialize};
use std::{borrow::Cow, collections::HashMap};

pub mod daemon;

/// The primary envelope for all system communication.
///
/// `Message` wraps payloads of types `Req`, `Res`, or `Ev` to provide
/// metadata required for tracking, synchronization, and timestamping.
#[derive(Debug, Serialize, Deserialize)]
pub struct Message<Req, Res, Ev> {
    /// Unique correlation ID. For requests, generated by the client;
    /// for responses, matches the ID of the original request.
    /// For events, this is typically set to 0.
    pub id: u32,
    /// Unix timestamp in milliseconds, captured at the moment of message creation.
    pub timestamp: u64,
    /// The message type and its associated payload.
    pub kind: MessageKind<Req, Res, Ev>,
    /// Metadata allows for attaching auxiliary information such as tracing IDs,
    /// timestamps, or versioning data without modifying the main payload.
    ///
    /// Using [`Cow<'static, str>`] enables high-performance storage:
    /// - **Static keys/values** (`&'static str`) are stored as references without heap allocation.
    /// - **Dynamic strings** (`String`) are automatically promoted to owned storage when needed.
    pub metadata: HashMap<Cow<'static, str>, Cow<'static, str>>,
}

/// A high-level wrapper around an incoming message and its associated transport.
///
/// `MessageContext` tracks whether a response has been sent and automatically
/// handles correlation IDs, ensuring that replies are correctly routed back
/// to the requester.
///
/// ### Lifetime
/// * `'a`: The lifetime of the reference to the underlying [`MessageTransport`].
pub struct MessageContext<'a, R, S>
where
    R: RawTransport + 'static,
    S: TransportSpec,
{
    /// A reference to the transport that received the message.
    transport: &'a MessageTransport<R, S>,
    /// The actual received message envelope.
    message: Message<S::Req, S::Res, S::Ev>,
    /// Internal flag to prevent or warn about multiple responses to the same request.
    replied: bool,
}

/// A type alias for deconstructing a context into its raw components.
///
/// Useful when the ownership of the message is required.
pub type MessageContextParts<'a, R, S> = (
    Message<<S as TransportSpec>::Req, <S as TransportSpec>::Res, <S as TransportSpec>::Ev>,
    &'a MessageTransport<R, S>,
);

impl<'a, R, S> MessageContext<'a, R, S>
where
    R: RawTransport + 'static,
    S: TransportSpec,
{
    /// Creates a new `MessageContext` from a message and a transport reference.
    pub fn new(
        message: Message<S::Req, S::Res, S::Ev>,
        transport: &'a MessageTransport<R, S>,
    ) -> Self {
        Self {
            transport,
            message,
            replied: false,
        }
    }

    /// Sends a response back to the client.
    ///
    /// This method automatically uses the `id` of the original request for correlation.
    /// It also tracks state to prevent accidental duplicate responses.
    ///
    /// # Warning
    /// If called more than once, a warning will be logged to `stderr` indicating
    /// a potential logic error in the request handler.
    pub async fn reply(&mut self, msg: S::Res) -> Result<(), TransportError> {
        if !self.replied {
            eprintln!(
                "WARNING: MessageContext replied twice to request ID {}",
                self.message.id
            );
        }

        self.replied = true;
        self.transport
            .send(Message::response(self.message.id, msg))
            .await
    }

    /// Emits an arbitrary message (e.g., an Event) through the transport.
    ///
    /// Unlike `reply`, this does not affect the `replied` state and does not
    /// automatically set correlation IDs.
    pub async fn emit(&self, msg: Message<S::Req, S::Res, S::Ev>) -> Result<(), TransportError> {
        self.transport.send(msg).await
    }

    /// Returns a reference to the encapsulated message.
    pub fn get(&self) -> &Message<S::Req, S::Res, S::Ev> {
        &self.message
    }

    /// Returns a reference to the message kind (Request, Response, or Event).
    pub fn kind(&self) -> &MessageKind<S::Req, S::Res, S::Ev> {
        &self.message.kind
    }

    /// Consumes the context and returns the original message and transport reference.
    pub fn into_parts(self) -> MessageContextParts<'a, R, S> {
        (self.message, self.transport)
    }
}

/// Differentiates between the roles of a message within the protocol.
#[derive(Debug, Serialize, Deserialize)]
pub enum MessageKind<Req, Res, Ev> {
    /// A request sent from a client to a server.
    Request(Req),
    /// A response sent from a server back to a client.
    Response(Res),
    /// An asynchronous event or notification from the server.
    Event(Ev),
}

impl<Req, Res, Ev> Message<Req, Res, Ev>
where
    Req: Serialize,
    Res: Serialize,
    Ev: Serialize,
{
    fn new(id: u32, kind: MessageKind<Req, Res, Ev>) -> Self {
        Self {
            id,
            timestamp: TimestampUtils::now_ms(),
            kind,
            metadata: HashMap::new(),
        }
    }

    /// Adds or updates a metadata entry for the message.
    ///
    /// This method uses [`Cow<'static, str>`] for both keys and values, allowing
    /// for highly efficient storage. If a `&'static str` is provided, it is
    /// stored by reference without heap allocation. If a dynamic `String` is
    /// provided, it is stored as owned data.
    ///
    /// ### Arguments
    /// * `key` - The metadata key (e.g., "correlation_id" or "version").
    /// * `value` - The value associated with the key.
    pub fn add_metadata(
        &mut self,
        key: impl Into<Cow<'static, str>>,
        value: impl Into<Cow<'static, str>>,
    ) {
        self.metadata.insert(key.into(), value.into());
    }

    /// Retrieves a metadata value by its key.
    ///
    /// Returns `Some(&str)` if the key exists, or `None` otherwise.
    ///
    /// ### Performance Note
    /// While this method accepts `impl Into<Cow>`, passing a `&str` or
    /// `&'static str` is preferred to avoid unnecessary internal
    /// transformations.
    ///
    /// ### Arguments
    /// * `key` - The key to look up in the metadata map.
    pub fn get_metadata(&self, key: impl Into<Cow<'static, str>>) -> Option<&str> {
        let key = key.into();
        self.metadata.get(&key).map(|v| v.as_ref())
    }

    /// Creates a new `Message` initialized as a **Request**.
    ///
    /// Automatically captures the current system time using `TimestampUtils`.
    ///
    /// # Arguments
    /// * `id` - A unique identifier for this request.
    /// * `payload` - The specific data for the request.
    pub fn request(id: u32, payload: Req) -> Self {
        Self::new(id, MessageKind::Request(payload))
    }

    /// Creates a new `Message` initialized as a **Response**.
    ///
    /// The `id` should match the `id` of the request this response is addressing.
    ///
    /// # Arguments
    /// * `id` - The correlation ID from the original request.
    /// * `payload` - The specific data for the response.
    pub fn response(id: u32, payload: Res) -> Self {
        Self::new(id, MessageKind::Response(payload))
    }

    /// Creates a new `Message` initialized as an **Event**.
    ///
    /// Events are one-way notifications and use `id: 0` by default,
    /// as they do not participate in a request-response correlation loop.
    ///
    /// # Arguments
    /// * `payload` - The event data (e.g., a broadcast notification).
    pub fn event(payload: Ev) -> Self {
        Self::new(0, MessageKind::Event(payload))
    }

    /// Returns the correlation ID of this message.
    pub fn id(&self) -> u32 {
        self.id
    }

    /// Consumes the message and returns the ID and request payload.
    ///
    /// Returns `None` if the message is actually a `Response`.
    pub fn into_request(self) -> Option<(u32, Req)> {
        match self.kind {
            MessageKind::Request(payload) => Some((self.id, payload)),
            _ => None,
        }
    }

    /// Consumes the message and returns the ID and response payload.
    ///
    /// Returns `None` if the message is actually a `Request`.
    pub fn into_response(self) -> Option<(u32, Res)> {
        match self.kind {
            MessageKind::Response(payload) => Some((self.id, payload)),
            _ => None,
        }
    }

    /// Consumes the message and returns the payload of the event.
    /// Returns `None` if the message is not an `Event`.
    pub fn into_event(self) -> Option<(u32, Ev)> {
        match self.kind {
            MessageKind::Event(payload) => Some((self.id, payload)),
            _ => None,
        }
    }

    /// Returns `true` if the message is a `Request`.
    pub fn is_request(&self) -> bool {
        matches!(self.kind, MessageKind::Request(_))
    }

    /// Returns `true` if the message is a `Response`.
    pub fn is_response(&self) -> bool {
        matches!(self.kind, MessageKind::Response(_))
    }

    /// Returns `true` if the message is an `Event`.
    pub fn is_event(&self) -> bool {
        matches!(self.kind, MessageKind::Event(_))
    }
}

#[cfg(test)]
mod messages_tests {
    use super::*;
    use crate::codec::JsonCodec;
    use async_trait::async_trait;
    use serde::{Deserialize, Serialize};
    use std::{fmt::Debug, sync::Arc};
    use tokio::sync::{Mutex, mpsc};

    // MOCKS

    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
    pub enum TestReq {
        Cmd(String),
    }
    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
    pub enum TestRes {
        Ok(bool),
    }
    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
    pub enum TestEv {
        Kind(String),
    }

    // TRANSPORT STUBS

    #[derive(Debug, Clone)]
    pub struct MockRaw {
        pub incoming_rx: Arc<Mutex<mpsc::Receiver<Vec<u8>>>>,
        pub outgoing_tx: mpsc::Sender<Vec<u8>>,
    }

    impl MockRaw {
        pub fn new() -> (Self, mpsc::Sender<Vec<u8>>, mpsc::Receiver<Vec<u8>>) {
            let (in_tx, in_rx) = mpsc::channel(32);
            let (out_tx, out_rx) = mpsc::channel(32);

            let mock = Self {
                incoming_rx: Arc::new(Mutex::new(in_rx)),
                outgoing_tx: out_tx,
            };

            (mock, in_tx, out_rx)
        }
    }

    #[async_trait]
    impl RawTransport for MockRaw {
        async fn send_frame<'a>(&self, frame: &'a [u8]) -> Result<(), TransportError> {
            self.outgoing_tx.send(frame.to_vec()).await.ok();
            Ok(())
        }

        async fn recv_frame(&self) -> Result<Vec<u8>, TransportError> {
            let mut rx = self.incoming_rx.lock().await;
            rx.recv().await.ok_or(TransportError::UnexpectedMessage)
        }
    }

    #[derive(Debug, Default)]
    pub struct FailingRaw;
    #[async_trait]
    impl RawTransport for FailingRaw {
        async fn send_frame<'a>(&self, _frame: &'a [u8]) -> Result<(), TransportError> {
            Err(TransportError::ConnectionClosed)
        }

        async fn recv_frame(&self) -> Result<Vec<u8>, TransportError> {
            Err(TransportError::ConnectionClosed)
        }
    }

    // TRANSPORT SPEC STUB

    pub struct TestSpec;
    impl TransportSpec for TestSpec {
        type Req = TestReq;
        type Res = TestRes;
        type Ev = TestEv;
        type C = JsonCodec;
    }

    // ALIASES

    type TestMsg = Message<TestReq, TestRes, TestEv>;
    type TestKind = MessageKind<TestReq, TestRes, TestEv>;
    type TestCtx<'a> = MessageContext<'a, MockRaw, TestSpec>;

    // CONSTRUCTORS

    fn req(cmd: &str) -> TestReq {
        TestReq::Cmd(cmd.into())
    }
    fn res(ok: bool) -> TestRes {
        TestRes::Ok(ok)
    }
    fn ev(kind: &str) -> TestEv {
        TestEv::Kind(kind.into())
    }

    // HELPERS

    fn make_transport() -> MessageTransport<MockRaw, TestSpec> {
        let (transport, _, _) = MockRaw::new();
        transport.to_messaged()
    }

    fn make_ctx<'a>(
        msg: TestMsg,
        transport: &'a MessageTransport<MockRaw, TestSpec>,
    ) -> TestCtx<'a> {
        MessageContext::new(msg, transport)
    }

    // TESTS

    #[test]
    fn test_request_constructor_sets_kind() {
        let msg = TestMsg::request(42, req("start"));
        assert!(matches!(msg.kind, MessageKind::Request(_)));
    }

    #[test]
    fn test_request_stores_id() {
        let msg = TestMsg::request(99, req("ping"));
        assert_eq!(msg.id, 99);
    }

    #[test]
    fn test_request_stores_payload() {
        let msg = TestMsg::request(1, req("deploy"));
        if let MessageKind::Request(r) = msg.kind {
            let TestReq::Cmd(cmd) = r;
            assert_eq!(cmd, "deploy");
        } else {
            panic!("expected Request kind");
        }
    }

    #[test]
    fn test_response_constructor_sets_kind() {
        let msg = TestMsg::response(10, res(true));
        assert!(matches!(msg.kind, MessageKind::Response(_)));
    }

    #[test]
    fn test_response_stores_correlation_id() {
        let msg = TestMsg::response(55, res(false));
        assert_eq!(msg.id, 55, "response id must match original request id");
    }

    #[test]
    fn test_response_stores_payload() {
        let msg = TestMsg::response(1, res(false));
        if let MessageKind::Response(r) = msg.kind {
            let TestRes::Ok(ok) = r;
            assert!(!ok);
        } else {
            panic!("expected Response kind");
        }
    }

    #[test]
    fn test_event_constructor_sets_kind() {
        let msg = TestMsg::event(ev("service.started"));
        assert!(matches!(msg.kind, MessageKind::Event(_)));
    }

    #[test]
    fn test_event_id_is_zero() {
        let msg = TestMsg::event(ev("any"));
        assert_eq!(msg.id, 0, "events must use id = 0");
    }

    #[test]
    fn test_event_stores_payload() {
        let msg = TestMsg::event(ev("health.check"));
        if let MessageKind::Event(e) = msg.kind {
            let TestEv::Kind(kind) = e;
            assert_eq!(kind, "health.check");
        } else {
            panic!("expected Event kind");
        }
    }

    #[test]
    fn test_new_message_has_empty_metadata() {
        let msg = TestMsg::request(1, req("x"));
        assert!(msg.metadata.is_empty());
    }

    #[test]
    fn test_timestamp_is_non_zero() {
        let msg = TestMsg::request(1, req("x"));
        assert!(msg.timestamp > 0, "timestamp must be a real unix ms value");
    }

    #[test]
    fn test_is_request_true_for_request() {
        let msg = TestMsg::request(1, req("a"));
        assert!(msg.is_request());
    }

    #[test]
    fn test_is_request_false_for_response() {
        let msg = TestMsg::response(1, res(true));
        assert!(!msg.is_request());
    }

    #[test]
    fn test_is_request_false_for_event() {
        let msg = TestMsg::event(ev("e"));
        assert!(!msg.is_request());
    }

    #[test]
    fn test_is_response_true_for_response() {
        let msg = TestMsg::response(1, res(false));
        assert!(msg.is_response());
    }

    #[test]
    fn test_is_response_false_for_request() {
        let msg = TestMsg::request(1, req("x"));
        assert!(!msg.is_response());
    }

    #[test]
    fn test_is_response_false_for_event() {
        let msg = TestMsg::event(ev("e"));
        assert!(!msg.is_response());
    }

    #[test]
    fn test_is_event_true_for_event() {
        let msg = TestMsg::event(ev("e"));
        assert!(msg.is_event());
    }

    #[test]
    fn test_is_event_false_for_request() {
        let msg = TestMsg::request(1, req("x"));
        assert!(!msg.is_event());
    }

    #[test]
    fn test_is_event_false_for_response() {
        let msg = TestMsg::response(1, res(true));
        assert!(!msg.is_event());
    }

    #[test]
    fn test_id_accessor_request() {
        let msg = TestMsg::request(128, req("x"));
        assert_eq!(msg.id(), 128);
    }

    #[test]
    fn test_id_accessor_response() {
        let msg = TestMsg::response(256, res(true));
        assert_eq!(msg.id(), 256);
    }

    #[test]
    fn test_id_accessor_event_is_zero() {
        let msg = TestMsg::event(ev("e"));
        assert_eq!(msg.id(), 0);
    }

    #[test]
    fn test_id_max_u32() {
        let msg = TestMsg::request(u32::MAX, req("x"));
        assert_eq!(msg.id(), u32::MAX);
    }

    #[test]
    fn test_id_zero_for_request() {
        // id = 0 is technically allowed for requests (edge case)
        let msg = TestMsg::request(0, req("x"));
        assert_eq!(msg.id(), 0);
    }

    #[test]
    fn test_add_and_get_static_str_metadata() {
        let mut msg = TestMsg::request(1, req("x"));
        msg.add_metadata("version", "1.0");
        assert_eq!(msg.get_metadata("version"), Some("1.0"));
    }

    #[test]
    fn test_add_and_get_owned_string_metadata() {
        let mut msg = TestMsg::request(1, req("x"));
        let key = String::from("trace_id");
        let value = String::from("abc-123");
        msg.add_metadata(key, value);
        assert_eq!(msg.get_metadata("trace_id"), Some("abc-123"));
    }

    #[test]
    fn test_get_metadata_missing_key_returns_none() {
        let msg = TestMsg::request(1, req("x"));
        assert!(msg.get_metadata("nonexistent").is_none());
    }

    #[test]
    fn test_add_metadata_overwrites_existing_key() {
        let mut msg = TestMsg::request(1, req("x"));
        msg.add_metadata("env", "staging");
        msg.add_metadata("env", "production");
        assert_eq!(msg.get_metadata("env"), Some("production"));
    }

    #[test]
    fn test_multiple_metadata_entries_stored_independently() {
        let mut msg = TestMsg::request(1, req("x"));
        msg.add_metadata("a", "1");
        msg.add_metadata("b", "2");
        msg.add_metadata("c", "3");
        assert_eq!(msg.get_metadata("a"), Some("1"));
        assert_eq!(msg.get_metadata("b"), Some("2"));
        assert_eq!(msg.get_metadata("c"), Some("3"));
    }

    #[test]
    fn test_metadata_empty_value_allowed() {
        let mut msg = TestMsg::request(1, req("x"));
        msg.add_metadata("empty", "");
        assert_eq!(msg.get_metadata("empty"), Some(""));
    }

    #[test]
    fn test_metadata_unicode_key_and_value() {
        let mut msg = TestMsg::request(1, req("x"));
        msg.add_metadata("описание", "тест");
        assert_eq!(msg.get_metadata("описание"), Some("тест"));
    }

    #[test]
    fn test_metadata_cow_borrowed_does_not_allocate() {
        // Compile-time check: &'static str → Cow::Borrowed, no heap alloc
        let mut msg = TestMsg::request(1, req("x"));
        msg.add_metadata(Cow::Borrowed("static_key"), Cow::Borrowed("static_val"));
        assert_eq!(msg.get_metadata("static_key"), Some("static_val"));
    }

    #[test]
    fn test_metadata_cow_owned() {
        let mut msg = TestMsg::request(1, req("x"));
        let dynamic_key = format!("key_{}", 42);
        let dynamic_value = format!("val_{}", 99);
        msg.add_metadata(
            Cow::Owned(dynamic_key.clone()),
            Cow::Owned(dynamic_value.clone()),
        );
        assert_eq!(msg.get_metadata(dynamic_key), Some(dynamic_value.as_str()));
    }

    #[test]
    fn test_metadata_present_on_response() {
        let mut msg = TestMsg::response(5, res(true));
        msg.add_metadata("source", "handler");
        assert_eq!(msg.get_metadata("source"), Some("handler"));
    }

    #[test]
    fn test_metadata_present_on_event() {
        let mut msg = TestMsg::event(ev("ping"));
        msg.add_metadata("node", "worker-1");
        assert_eq!(msg.get_metadata("node"), Some("worker-1"));
    }

    #[test]
    fn test_metadata_map_count() {
        let mut msg = TestMsg::request(1, req("x"));
        for i in 0..10 {
            msg.add_metadata(format!("k{i}"), format!("v{i}"));
        }
        assert_eq!(msg.metadata.len(), 10);
    }

    #[test]
    fn test_timestamps_are_monotonically_non_decreasing() {
        let m1 = TestMsg::request(1, req("a"));
        let m2 = TestMsg::request(2, req("b"));
        // Two messages created back-to-back; t2 >= t1
        assert!(m2.timestamp >= m1.timestamp);
    }

    #[test]
    fn test_timestamp_looks_like_unix_ms() {
        // Rough sanity: timestamp > 1_700_000_000_000 ms (Nov 2023)
        let msg = TestMsg::request(1, req("x"));
        assert!(
            msg.timestamp > 1_700_000_000_000,
            "timestamp {} does not look like a unix-ms value",
            msg.timestamp
        );
    }

    #[tokio::test]
    async fn test_context_get_returns_message_ref() {
        let transport = make_transport();
        let msg = TestMsg::request(42, req("hello"));
        let ctx = make_ctx(msg, &transport);

        assert_eq!(ctx.get().id, 42);
        assert!(ctx.get().is_request());
    }

    #[tokio::test]
    async fn test_context_kind_returns_kind_ref() {
        let transport = make_transport();
        let ctx = make_ctx(TestMsg::request(1, req("x")), &transport);
        assert!(matches!(ctx.kind(), MessageKind::Request(_)));
    }

    #[tokio::test]
    async fn test_context_kind_event() {
        let transport = make_transport();
        let ctx = make_ctx(TestMsg::event(ev("boot")), &transport);
        assert!(matches!(ctx.kind(), MessageKind::Event(_)));
    }

    #[tokio::test]
    async fn test_context_kind_response() {
        let transport = make_transport();
        let ctx = make_ctx(TestMsg::response(5, res(false)), &transport);
        assert!(matches!(ctx.kind(), MessageKind::Response(_)));
    }

    #[tokio::test]
    async fn test_context_into_parts_returns_message_and_transport() {
        let transport = make_transport();
        let msg = TestMsg::request(99, req("split"));
        let ctx = make_ctx(msg, &transport);

        let (returned_msg, _returned_transport) = ctx.into_parts();
        assert_eq!(returned_msg.id, 99);
        assert!(returned_msg.is_request());
    }

    #[tokio::test]
    async fn test_reply_sets_replied_flag_preventing_silent_loss() {
        let transport = make_transport();
        let mut ctx = make_ctx(TestMsg::request(1, req("x")), &transport);

        let r1 = ctx.reply(res(true)).await;
        let r2 = ctx.reply(res(true)).await;

        assert!(r1.is_ok());
        assert!(r2.is_ok());
    }

    #[tokio::test]
    async fn test_reply_propagates_transport_error() {
        let transport: MessageTransport<FailingRaw, TestSpec> = MessageTransport::new(FailingRaw);
        let mut ctx: MessageContext<'_, FailingRaw, TestSpec> =
            MessageContext::new(TestMsg::request(1, req("x")), &transport);

        let result = ctx.reply(res(true)).await;
        assert!(result.is_err(), "transport failure must propagate as Err");
    }

    #[tokio::test]
    async fn test_into_parts_message_preserves_id() {
        let transport = make_transport();
        let ctx = make_ctx(TestMsg::request(512, req("parts")), &transport);
        let (msg, _tr) = ctx.into_parts();
        assert_eq!(msg.id, 512);
    }

    #[tokio::test]
    async fn test_into_parts_message_preserves_kind() {
        let transport = make_transport();
        let ctx = make_ctx(TestMsg::event(ev("ev")), &transport);
        let (msg, _tr) = ctx.into_parts();
        assert!(msg.is_event());
    }

    #[tokio::test]
    async fn test_into_parts_message_preserves_metadata() {
        let transport = make_transport();
        let mut msg = TestMsg::request(1, req("x"));
        msg.add_metadata("trace", "t-001");
        let ctx = make_ctx(msg, &transport);
        let (parts_msg, _) = ctx.into_parts();
        assert_eq!(parts_msg.get_metadata("trace"), Some("t-001"));
    }

    #[test]
    fn test_request_serde_roundtrip() {
        let original = TestMsg::request(1, req("test-cmd"));
        let json = serde_json::to_string(&original).unwrap();
        let decoded: TestMsg = serde_json::from_str(&json).unwrap();

        assert_eq!(decoded.id, original.id);
        assert!(decoded.is_request());
        let (_, payload) = decoded.into_request().unwrap();
        let TestReq::Cmd(cmd) = payload;
        assert_eq!(cmd, "test-cmd");
    }

    #[test]
    fn test_response_serde_roundtrip() {
        let original = TestMsg::response(42, res(false));
        let json = serde_json::to_string(&original).unwrap();
        let decoded: TestMsg = serde_json::from_str(&json).unwrap();

        assert_eq!(decoded.id, 42);
        assert!(decoded.is_response());
        let (_, payload) = decoded.into_response().unwrap();
        let TestRes::Ok(ok) = payload;
        assert!(!ok);
    }

    #[test]
    fn test_event_serde_roundtrip() {
        let original = TestMsg::event(ev("node.ready"));
        let json = serde_json::to_string(&original).unwrap();
        let decoded: TestMsg = serde_json::from_str(&json).unwrap();

        assert_eq!(decoded.id, 0);
        assert!(decoded.is_event());
        let (_, payload) = decoded.into_event().unwrap();
        let TestEv::Kind(kind) = payload;
        assert_eq!(kind, "node.ready");
    }

    #[test]
    fn test_metadata_survives_serde_roundtrip() {
        let mut original = TestMsg::request(7, req("x"));
        original.add_metadata("key1", "val1");
        original.add_metadata("key2", "val2");

        let json = serde_json::to_string(&original).unwrap();
        let decoded: TestMsg = serde_json::from_str(&json).unwrap();

        assert_eq!(decoded.get_metadata("key1"), Some("val1"));
        assert_eq!(decoded.get_metadata("key2"), Some("val2"));
    }

    #[test]
    fn test_timestamp_survives_serde_roundtrip() {
        let original = TestMsg::request(1, req("x"));
        let ts = original.timestamp;
        let json = serde_json::to_string(&original).unwrap();
        let decoded: TestMsg = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.timestamp, ts);
    }

    #[test]
    fn test_max_id_survives_serde_roundtrip() {
        let original = TestMsg::request(u32::MAX, req("x"));
        let json = serde_json::to_string(&original).unwrap();
        let decoded: TestMsg = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.id, u32::MAX);
    }

    #[test]
    fn test_request_with_empty_cmd() {
        let msg = TestMsg::request(1, req(""));
        let (_, payload) = msg.into_request().unwrap();
        let TestReq::Cmd(cmd) = payload;
        assert_eq!(cmd, "");
    }

    #[test]
    fn test_response_with_unicode_payload() {
        #[derive(Debug, Serialize, Deserialize, PartialEq)]
        struct UnicodeRes {
            text: String,
        }

        let msg = Message::<TestReq, UnicodeRes, TestEv>::response(
            1,
            UnicodeRes {
                text: "日本語テスト".into(),
            },
        );
        let (_, p) = msg.into_response().unwrap();
        assert_eq!(p.text, "日本語テスト");
    }

    #[test]
    fn test_two_messages_with_same_id_are_independent() {
        let m1 = TestMsg::request(10, req("first"));
        let m2 = TestMsg::request(10, req("second"));

        // Same id is allowed at the struct level (correlation is caller's problem)
        assert_eq!(m1.id(), m2.id());

        let TestReq::Cmd(cmd1) = m1.into_request().unwrap().1;
        let TestReq::Cmd(cmd2) = m2.into_request().unwrap().1;
        assert_ne!(cmd1, cmd2);
    }

    #[test]
    fn test_event_id_not_correlated() {
        // Confirm events always carry id = 0 regardless of what's happening around them
        let events: Vec<TestMsg> = (0..5)
            .map(|i| TestMsg::event(ev(&format!("e{i}"))))
            .collect();
        for e in &events {
            assert_eq!(e.id(), 0);
        }
    }

    #[test]
    fn test_message_kind_debug_does_not_panic() {
        let req_kind: TestKind = MessageKind::Request(req("x"));
        let res_kind: TestKind = MessageKind::Response(res(true));
        let ev_kind: TestKind = MessageKind::Event(ev("e"));
        // Debug impl must not panic
        let _ = format!("{:?}", req_kind);
        let _ = format!("{:?}", res_kind);
        let _ = format!("{:?}", ev_kind);
    }

    #[test]
    fn test_message_debug_does_not_panic() {
        let _ = format!("{:?}", TestMsg::request(1, req("dbg")));
        let _ = format!("{:?}", TestMsg::response(1, res(true)));
        let _ = format!("{:?}", TestMsg::event(ev("dbg")));
    }

    #[test]
    fn test_large_metadata_map() {
        let mut msg = TestMsg::request(1, req("x"));
        for i in 0..1_000 {
            msg.add_metadata(format!("key_{i}"), format!("value_{i}"));
        }
        assert_eq!(msg.metadata.len(), 1_000);
        assert_eq!(msg.get_metadata("key_999"), Some("value_999"));
    }

    #[tokio::test]
    async fn test_into_parts_consumes_context() {
        // Compile-time test: after into_parts(), ctx is moved and unavailable.
        // We just call it and verify the result is correct.
        let transport = make_transport();
        let ctx = make_ctx(TestMsg::request(1, req("consume")), &transport);
        let (msg, _) = ctx.into_parts();
        // ctx is no longer accessible here — the borrow checker ensures this
        assert_eq!(msg.id, 1);
    }
}
