[package]
name = "knot-transport"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
autobenches = false

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = "1.52.1"
knot-core = { path="../core" }
async-trait = "0.1.89"
interprocess = { version = "2.4.2", features = ["tokio"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
rstest = "0.26.1"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
dashmap = "6.1.0"
futures = "0.3.32"

[dev-dependencies]
tokio = { version = "1.52.1", features = ["full", "test-util"] }
criterion = { version = "0.8.2", features = ["async_tokio"] }

[[test]]
name = "integration"
path = "tests/integration_tests.rs"

[[test]]
name = "stress"
path = "tests/stress_tests.rs"

[[bench]]
name = "transport_bench"
harness = false