name: Buf Checks

on:
  push:
    branches:
      - main
    paths:
      - 'proto/**'
      - 'buf.yaml'
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
    paths:
      - 'proto/**'
      - 'buf.yaml'
  delete:

permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          version: "1.72.0"